"""The preview showed the box to tick, never what the document says.

Four product documents wait at once and their sign-off sections are near-identical —
`- [ ] Read and holds`, four times. A batch preview of those four distinguishes them by
path alone, which puts the operator in the position the whole gate exists to prevent:
ticking a box whose subject they are taking on trust.

So each preview opens with what the document IS, and every line of it is EXTRACTED —
title, section headings, size, last change. Nothing here is generated or summarised by
a model: a "summary" this tool invented would be one more thing the reader has to
verify, and the signature already asserts they read the document itself.

`SOP.md` step 3 stays exactly where it is — *"Read the document itself. The preview
shows the checklist, not the work."* This makes the preview say which work, not replace
the reading.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
_SCRIPT = _ROOT / "skills" / "sign" / "scripts" / "sign_document.py"

_DOCUMENT = """# Product vision — checkout redesign

> Generated by `/brainstorm-pieces`.

## The problem

Something long enough to count.

## Who it is for

More words here.

## Out of scope

And here.

## Sign-off

- [ ] The problem stated is the real one
"""


def _doc(tmp_path: Path, name: str = "vision.md", body: str = _DOCUMENT) -> Path:
    path = tmp_path / name
    path.write_text(body, encoding="utf-8")
    return path


def _preview(document: Path) -> str:
    done = subprocess.run(
        [sys.executable, str(_SCRIPT), str(document), "--as", "paulo"],
        capture_output=True, text=True, timeout=120, check=False)
    return done.stdout + done.stderr


def test_the_title_is_shown(tmp_path: Path) -> None:
    """Four paths ending in `.md` are not four subjects."""
    out = _preview(_doc(tmp_path))

    assert "Product vision — checkout redesign" in out, (
        "the preview never said what the document is:\n" + out)


def test_the_sections_are_shown(tmp_path: Path) -> None:
    """What the document covers, in its own headings — the closest thing to a summary
    that is not an invention."""
    out = _preview(_doc(tmp_path))

    for heading in ("The problem", "Who it is for", "Out of scope"):
        assert heading in out, f"section {heading!r} missing from the preview:\n{out}"


def test_the_sign_off_section_is_not_listed_as_content(tmp_path: Path) -> None:
    """It is already shown verbatim below. Listing it among the sections pads the
    summary with the one heading the reader is not being asked to judge."""
    out = _preview(_doc(tmp_path))
    header = out.split("The sign-off section, verbatim:")[0]

    assert "Sign-off" not in header.replace("ABOUT TO SIGN", ""), (
        "the sign-off heading was counted as document content:\n" + header)


def test_the_size_is_shown(tmp_path: Path) -> None:
    """A one-line stub and a 300-line brief ask for different amounts of reading, and
    the preview should say which one is in front of you."""
    out = _preview(_doc(tmp_path))

    assert "line" in out.lower(), "the preview does not say how long the document is"


def test_a_document_with_no_headings_says_so(tmp_path: Path) -> None:
    """Absence stated, never left blank. An empty section list reads as "nothing to
    see" when it means "this tool found no headings" — the same confusion the `--list`
    output already refuses to create."""
    out = _preview(_doc(tmp_path, "bare.md",
                        "Just prose.\n\n## Sign-off\n\n- [ ] Read and holds\n"))

    lowered = out.lower()
    assert "no heading" in lowered or "untitled" in lowered or "no section" in lowered, (
        "a document with no structure previewed as though it had some:\n" + out)


def test_nothing_in_the_summary_is_invented(tmp_path: Path) -> None:
    """Every word of the summary must appear in the document or be a count.

    This is the test that keeps the feature honest as it grows: the moment someone adds
    a generated one-line description, this fails, and it should — a summary the reader
    has to verify is worse than no summary, because the signature already asserts they
    read the thing.
    """
    out = _preview(_doc(tmp_path))
    header = out.split("The sign-off section, verbatim:")[0]
    document_words = set(_DOCUMENT.lower().split())

    invented = [w for w in header.lower().split()
                if w.isalpha() and len(w) > 4 and w not in document_words
                and w not in {"about", "section", "sign", "verbatim", "lines", "words",
                              "heading", "headings", "sections", "signing", "authors",
                              "record", "unticked", "boxes", "changed", "could", "untitled"}]

    assert not invented, (
        f"these words are in the preview and not in the document: {sorted(set(invented))}")
